
sheet_name = 'import@Tasks'
configuration_name = 'configuration_name'
object_id = 'ID'
task_type = 'TaskType'
task_params = 'TaskParams'
task_stages = 'TaskStages'
text_loc_key = 'TextLocKey'
icon = 'Icon'
maps = 'Map'
maps_groups = 'MapGroups'
