# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Stages Validate and Compare

on:
  workflow_dispatch:
    inputs:
      google_sheet_url:
        description: "Google Sheet URL"
        required: true
      event_id:
        description: "Event ID"
        required: true
        type: string
      config_branch_name:
        description: "Config Branch Name"
        type: string
        required: true


permissions:
  contents: read

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - MA-Platform

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list

    - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_GAME_CONTROL_CI_SA }}
          access_token_lifetime: '600s'
    - name: Pull secrets from secret manager
        id: pull-secrets
        uses: google-github-actions/get-secretmanager-secrets@v1
        with:
          secrets: |-
            ma_user:${{ secrets.MA_USER_SECRET }}
            ma_password:${{ secrets.MA_PASSWORD_SECRET }}
